// Code not generated by ChatGPT but functions and methods were searched for using ChatGPT. Sadly all the code was painstakingly handwritten (I need to learn frameworks)
const mainContainer = document.querySelector("main");

let containerNum = 1;
const arrestedDevelopment = {
  image: "images/ArrestedDevelopment.jpg",
  description: "Arrested Development is an American television sitcom created by Mitchell Hurwitz. It aired on Fox for three seasons from November 2, 2003, to February 10, 2006, followed by two seasons on Netflix, season four being released in 2013 and season five being released in 2018 and 2019.",
  genre: "Comedy",
  recommenders: ["Tessa", "Andrew", "LeeAnn", "Jenaya", "Jeffrey"]
}

const kimsConvenience = {
    image: "images/KimsConvenience.jpg",
    description: "Kim's Convenience (Korean: 김씨네 편의점; Hanja: 金氏네 便宜店; RR: Gimssine Pyeonuijeon) is a Canadian television sitcom that aired on CBC Television from October 2016 to April 2021. It depicts the Korean Canadian Kim family that runs a convenience store in the Moss Park neighbourhood of Toronto: parents \"Appa\" (Paul Sun-Hyung Lee) and \"Umma\" (Jean Yoon) – Korean for dad and mom, respectively – along with their daughter Janet (Andrea Bang) and estranged son Jung (Simu Liu). Other characters include Jung's friend and coworker Kimchee (Andrew Phung), his manager Shannon (Nicole Power) and Janet's friend Gerald Tremblay (Ben Beauchemin). The series is based on Ins Choi's 2011 play of the same name.",
    genre: "Comedy",
    recommenders: ["Andrew"]
}

showlist = [arrestedDevelopment, kimsConvenience];

function serverRequest () {
    fetch("http://127.0.0.1:5000/reciever",
        {
            method: 'POST',
            headers: {
                'Content-type': 'application/json',
                //'Accept': 'application/json'
            },
            /*body:JSON.stringify(showlist)*/}).then(res=>{
                if(res.ok){
                    return res.json()
                }else{
                    alert("Something is wrong")
                }
            }).then(jsonResponse=>{
                createShowRec(jsonResponse)
            }
            ).catch((err) => console.error(err));

}

function createShowRec (show) {
    let showContainer = document.createElement("div");
    showContainer.className = "showContainer";
    showContainer.id = `show-${containerNum}`;

    let showImage = document.createElement("img");
    showImage.className = "showImage";
    showImage.id = `showImg-${containerNum}`;
    showImage.src = `http://127.0.0.1:5000/images?image_file_name=${show["image"]}`;
    showContainer.appendChild(showImage);

    let showText = document.createElement("div");
    showText.className = "showText";
    showText.id = `showText-${containerNum}`;

    let showDesc = document.createElement("p");
    showDesc.className = "showDesc";
    showDesc.textContent = show["description"];
    showText.appendChild(showDesc);

    let showGenre = document.createElement("p");
    showGenre.className = "showGenre";
    showGenre.textContent = `Genre: ${show["genre"]}`;
    showText.appendChild(showGenre);

    let recommenders = document.createElement("p");
    recommenders.className = "recommenders";
    recommenders.textContent = "Recommenders: ";
    
    for (let i = 0; i < Math.min(show["recommenders"].length, 4); i++) {
        let recommender = document.createElement("span");
        recommender.textContent = show["recommenders"][i];
        recommenders.appendChild(recommender);
    }
    
    showText.appendChild(recommenders);

    showContainer.appendChild(showText);
    containerNum++;
    mainContainer.appendChild(showContainer);
}

// Bottom of page dectector from stackOverflow's Dekel at https://stackoverflow.com/questions/9439725/how-to-detect-if-browser-window-is-scrolled-to-bottom

for (let i = 0; i < 10; i++) {
    serverRequest();
}

window.onscroll = function(ev) {
    serverRequest();
};


myButton.onclick = () => {
    serverRequest();
};